// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-PoMXLLNMVABPWrNLK_kDgIYTa9PxBI',
    appId: '1:164213565917:web:0a8141f0e2f73f87eeee34',
    messagingSenderId: '164213565917',
    projectId: 'chat-98a70',
    authDomain: 'chat-98a70.firebaseapp.com',
    storageBucket: 'chat-98a70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBWWMlF8I6OpXTx_tIbgg7DypVTl-cOo',
    appId: '1:164213565917:android:7d76df7193248f5aeeee34',
    messagingSenderId: '164213565917',
    projectId: 'chat-98a70',
    storageBucket: 'chat-98a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJeFXjCSlKYn30ljsisnOwWq3zP9NkQXs',
    appId: '1:164213565917:ios:c6c16a6fb4b82b4deeee34',
    messagingSenderId: '164213565917',
    projectId: 'chat-98a70',
    storageBucket: 'chat-98a70.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
